/**
 * API oPROsita
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Archivo { 
    id?: number;
    nombre?: string;
    tipo?: string;
    url?: string;
    datos?: string;
}

