/**
 * API oPROsita
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContenidoItem { 
    id?: number;
    texto?: string;
    tipoContenido?: ContenidoItem.TipoContenidoEnum;
    alumnoId?: number | null;
    grupoId?: number;
    mes?: string;
    archivoId?: number | null;
}
export namespace ContenidoItem {
    export const TipoContenidoEnum = {
        Temas: 'temas',
        Programacion: 'programacion',
        Practico: 'practico'
    } as const;
    export type TipoContenidoEnum = typeof TipoContenidoEnum[keyof typeof TipoContenidoEnum];
}


