/**
 * API oPROsita
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Conversacion { 
    id?: number;
    usuarioId?: number;
    otroUsuarioId?: number;
    ultimoMensaje?: string;
    fechaUltimoMensaje?: string;
    noLeidos?: number;
}

