/**
 * API oPROsita
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Mensaje { 
    id?: number;
    /**
     * ID del usuario remitente
     */
    remitente?: number;
    /**
     * ID del usuario destinatario
     */
    destinatario?: number;
    contenido?: string;
    leido?: boolean;
    fechaEnvio?: string;
}

