/**
 * API oPROsita
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Usuario } from './usuario';


export interface Profesor extends Usuario { 
    tipo?: Profesor.TipoEnum;
}
export namespace Profesor {
    export const TipoEnum = {
        Profesor: 'profesor'
    } as const;
    export type TipoEnum = typeof TipoEnum[keyof typeof TipoEnum];
}


