services:

  mysql:
    build:
      context: ./backend/docker/mysql
      dockerfile: Dockerfile
    container_name: mysql-container
    ports:
      - "3306:3306"
    networks:
      - my-network

  backend:
    depends_on:
      - mysql
      - openapi-builder
    build:
      context: ./backend
      dockerfile: ./docker/backend/Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    networks:
      - my-network
    entrypoint: ["sh", "-c", "until nc -z mysql 3306; do echo 'Waiting for MySQL...'; sleep 2; done; java -jar /app/myapp.jar"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "4200:80"
    networks:
      - my-network
    depends_on:
      - backend

  openapi-builder:
    build:
      context: ./openapi
      dockerfile: Dockerfile
    volumes:
      - C:/Users/dgp8/.m2:/root/.m2  # Caché Maven
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
