openapi: 3.0.3
info:
  title: API oPROsita
  description: API REST para gestión de grupos, usuarios, contenido y simulacros
  version: 1.0.1

servers:
  - url: http://localhost:8080/api

tags:
  - name: grupos
    description: Operaciones con grupos de alumnos
  - name: alumnos
    description: Gestión de alumnos
  - name: contenido
    description: Gestión de contenido educativo
  - name: simulacros
    description: Operaciones con simulacros de examen
  - name: novedades
    description: Sistema de novedades y notificaciones
  - name: noticias
    description: Gestión de noticias
  - name: archivos
    description: Gestión de archivos y documentos

paths:
  /grupos:
    get:
      tags:
        - grupos
      operationId: getGrupos
      summary: Obtener todos los grupos
      responses:
        '200':
          description: Lista de grupos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Grupo'
        '500':
          description: Error interno
    post:
      tags:
        - grupos
      operationId: createGrupo
      summary: Crear un nuevo grupo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Grupo'
      responses:
        '201':
          description: Grupo creado

  /grupos/{id}:
    get:
      tags:
        - grupos
      operationId: getGrupoById
      summary: Obtener detalle de un grupo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Grupo encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Grupo'
        '404':
          description: Grupo no encontrado
    put:
      tags:
        - grupos
      operationId: updateGrupo
      summary: Actualizar un grupo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Grupo'
      responses:
        '200':
          description: Grupo actualizado
    delete:
      tags:
        - grupos
      operationId: deleteGrupo
      summary: Eliminar un grupo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Grupo eliminado correctamente
        '404':
          description: Grupo no encontrado

  /grupos/{grupoId}/alumnos:
    get:
      tags:
        - grupos
        - alumnos
      operationId: getAlumnosByGrupo
      summary: Obtener alumnos de un grupo
      parameters:
        - in: path
          name: grupoId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lista de alumnos
    post:
      tags:
        - grupos
        - alumnos
      operationId: addAlumnoToGrupo
      summary: Añadir un alumno a un grupo
      parameters:
        - in: path
          name: grupoId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alumno'
      responses:
        '201':
          description: Alumno añadido

  /grupos/{grupoId}/alumnos/{alumnoId}:
    delete:
      tags:
        - grupos
        - alumnos
      operationId: removeAlumnoFromGrupo
      summary: Eliminar un alumno de un grupo
      parameters:
        - in: path
          name: grupoId
          required: true
          schema:
            type: integer
        - in: path
          name: alumnoId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Alumno eliminado correctamente del grupo

  /alumnos/{id}:
    delete:
      tags:
        - alumnos
      operationId: deleteAlumno
      summary: Eliminar un alumno
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Alumno eliminado correctamente

  /alumnos/{alumnoId}/contenido:
    get:
      tags:
        - alumnos
        - contenido
      operationId: getContenidoByAlumno
      summary: Obtener contenido de un alumno
      parameters:
        - in: path
          name: alumnoId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lista de contenido

    post:
      tags:
        - alumnos
        - contenido
      operationId: addContenidoToAlumno
      summary: Añadir contenido al alumno (texto + tipo + PDF)
      parameters:
        - in: path
          name: alumnoId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                texto:
                  type: string
                tipoContenido:
                  type: string
                  enum: [ temas, programacion, practico ]
                mes:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Contenido añadido

  /alumnos/{alumnoId}/contenido/{contenidoId}:
    delete:
      tags:
        - alumnos
        - contenido
      operationId: deleteContenidoFromAlumno
      summary: Eliminar un contenido del alumno
      parameters:
        - in: path
          name: alumnoId
          required: true
          schema:
            type: integer
        - in: path
          name: contenidoId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Contenido eliminado correctamente

  /grupos/{grupoId}/meses/{mes}/contenido:
    get:
      tags:
        - grupos
        - contenido
      operationId: getContenidoByGrupoAndMes
      summary: Obtener contenido por grupo y mes
      parameters:
        - in: path
          name: grupoId
          required: true
          schema:
            type: integer
        - in: path
          name: mes
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de contenido
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContenidoItem'
    post:
      tags:
        - grupos
        - contenido
      operationId: addContenidoToGrupoByMes
      summary: Añadir contenido a un grupo en un mes
      parameters:
        - in: path
          name: grupoId
          required: true
          schema:
            type: integer
        - in: path
          name: mes
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContenidoItem'
      responses:
        '201':
          description: Contenido añadido

  /contenido/{id}:
    delete:
      tags:
        - contenido
      operationId: deleteContenido
      summary: Eliminar un contenido
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Contenido eliminado correctamente
    put:
      tags:
        - contenido
      operationId: updateContenido
      summary: Actualizar un contenido
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContenidoItem'
      responses:
        '200':
          description: Contenido actualizado

  /simulacros:
    get:
      tags:
        - simulacros
      operationId: getSimulacros
      summary: Obtener simulacros
      responses:
        '200':
          description: Lista de simulacros
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Simulacro'

    post:
      tags:
        - simulacros
      operationId: createSimulacro
      summary: Crear un nuevo simulacro (PDF + descripción)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                descripcion:
                  type: string
                grupoId:
                  type: integer
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Simulacro creado

  /simulacros/{id}:
    delete:
      tags:
        - simulacros
      operationId: deleteSimulacro
      summary: Eliminar un simulacro
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Simulacro eliminado correctamente

  /novedades/profesor:
    get:
      tags:
        - novedades
      operationId: getNovedadesProfesor
      summary: Obtener novedades para profesores
      responses:
        '200':
          description: Lista de novedades
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Novedad'

    post:
      tags:
        - novedades
      operationId: createNovedadProfesor
      summary: Crear novedad para profesores
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Novedad'
      responses:
        '201':
          description: Novedad creada

  /novedades/alumno:
    get:
      tags:
        - novedades
      operationId: getNovedadesAlumno
      summary: Obtener novedades para alumnos
      responses:
        '200':
          description: Lista de novedades
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Novedad'

    post:
      tags:
        - novedades
      operationId: createNovedadAlumno
      summary: Crear novedad para alumnos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Novedad'
      responses:
        '201':
          description: Novedad creada

    put:
      tags:
        - novedades
      operationId: updateNovedadAlumno
      summary: Actualizar novedad para alumno
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Novedad'
      responses:
        '200':
          description: Novedad actualizada

    delete:
      tags:
        - novedades
      operationId: deleteNovedadesAlumno
      summary: Eliminar todas las novedades para alumno
      responses:
        '204':
          description: Novedades eliminadas correctamente

  /novedades/{id}:
    delete:
      tags:
        - novedades
      operationId: deleteNovedad
      summary: Eliminar una novedad
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Novedad eliminada correctamente

  /noticias:
    get:
      tags:
        - noticias
      operationId: getNoticias
      summary: Obtener noticias
      responses:
        '200':
          description: Lista de noticias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Noticia'

    post:
      tags:
        - noticias
      operationId: createNoticia
      summary: Crear una nueva noticia (PDF + descripción)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                descripcion:
                  type: string
                grupoId:
                  type: integer
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Noticia creada
  /noticias/{id}:
    delete:
      tags:
        - noticias
      operationId: deleteNoticia
      summary: Eliminar una noticia
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Noticia eliminada correctamente

  /archivos/upload:
    post:
      tags:
        - archivos
      operationId: uploadArchivo
      summary: Subir archivo
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Archivo subido correctamente

  /archivos/{id}/download:
    get:
      tags:
        - archivos
      operationId: downloadArchivo
      summary: Descargar archivo por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Archivo descargado
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Archivo no encontrado
components:
  schemas:
    Grupo:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        meses:
          type: array
          items:
            $ref: '#/components/schemas/Mes'

    Mes:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string

    Usuario:
      type: object
      discriminator:
        propertyName: tipo
      properties:
        id:
          type: integer
        nombre:
          type: string
        grupoId:
          type: integer

    Alumno:
      allOf:
        - $ref: '#/components/schemas/Usuario'
        - type: object
          properties:
            tipo:
              type: string
              enum: [alumno]

    Profesor:
      allOf:
        - $ref: '#/components/schemas/Usuario'
        - type: object
          properties:
            tipo:
              type: string
              enum: [profesor]

    ContenidoItem:
      type: object
      properties:
        id:
          type: integer
        texto:
          type: string
        tipoContenido:
          type: string
          enum: [temas, programacion, practico]
        alumnoId:
          type: integer
          nullable: true
        grupoId:
          type: integer
        mes:
          type: string
        archivoId:
          type: integer
          nullable: true

    Archivo:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        tipo:
          type: string
        url:
          type: string
        datos:
          type: string
          format: byte

    Simulacro:
      type: object
      properties:
        id:
          type: integer
        descripcion:
          type: string
        archivoId:
          type: integer
        grupoId:
          type: integer

    Novedad:
      type: object
      properties:
        id:
          type: integer
        texto:
          type: string
        tipoDestinatario:
          type: string
          enum: [profesor, alumno]
        fechaCreacion:
          type: string
          format: date-time

    Noticia:
      type: object
      properties:
        id:
          type: integer
        descripcion:
          type: string
        archivoId:
          type: integer
        grupoId:
          type: integer