spring:
  profiles:
    active: local
  datasource:
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/oprosita

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  servlet:
    context-path: /api