spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/mydatabase
  security:
    oauth2:
      resource server:
        jwt:
          # issuer-uri: http://keycloak:8080/realms/oprosita
          jwk-set-uri: http://keycloak:8080/realms/oprosita/protocol/openid-connect/certs