export * from './alumnos.service';
import { AlumnosService } from './alumnos.service';
export * from './archivos.service';
import { ArchivosService } from './archivos.service';
export * from './contenido.service';
import { ContenidoService } from './contenido.service';
export * from './grupos.service';
import { GruposService } from './grupos.service';
export * from './noticias.service';
import { NoticiasService } from './noticias.service';
export * from './novedades.service';
import { NovedadesService } from './novedades.service';
export * from './simulacros.service';
import { SimulacrosService } from './simulacros.service';
export const APIS = [AlumnosService, ArchivosService, ContenidoService, GruposService, NoticiasService, NovedadesService, SimulacrosService];
