export * from './alumnos.service';
import { AlumnosService } from './alumnos.service';
export * from './archivos.service';
import { ArchivosService } from './archivos.service';
export * from './chat.service';
import { ChatService } from './chat.service';
export * from './contenido.service';
import { ContenidoService } from './contenido.service';
export * from './grupos.service';
import { GruposService } from './grupos.service';
export * from './meses.service';
import { MesesService } from './meses.service';
export * from './noticias.service';
import { NoticiasService } from './noticias.service';
export * from './novedades.service';
import { NovedadesService } from './novedades.service';
export * from './profesores.service';
import { ProfesoresService } from './profesores.service';
export * from './reuniones.service';
import { ReunionesService } from './reuniones.service';
export * from './simulacros.service';
import { SimulacrosService } from './simulacros.service';
export const APIS = [AlumnosService, ArchivosService, ChatService, ContenidoService, GruposService, MesesService, NoticiasService, NovedadesService, ProfesoresService, ReunionesService, SimulacrosService];
