name: Build and Push Keycloak Image

on:
  workflow_dispatch:

jobs:
  build-and-push-keycloak:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract Keycloak version from theme.properties
        id: extract_version
        run: |
          VERSION=$(grep '^version=' keycloak/themes/oprosita/theme.properties | cut -d'=' -f2)
          echo "Versión detectada: $VERSION"
          echo "keycloak_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and Push Keycloak Image
        run: |
          docker build -t ${DOCKERHUB_USERNAME}/oprosita-keycloak:${{ steps.extract_version.outputs.keycloak_version }} -f keycloak/Dockerfile ./keycloak
          docker push ${DOCKERHUB_USERNAME}/oprosita-keycloak:${{ steps.extract_version.outputs.keycloak_version }}
