name: Build and Push OpenAPI to DockerHub

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # ---------- Copy openapi.yml to openapi-backend ----------
      - name: Copy openapi.yml to openapi-backend
        run: cp openapi/openapi.yml openapi/openapi-backend/openapi.yml

      - name: Build OpenAPI JAR (backend)
        working-directory: ./openapi/openapi-backend
        env:
          WORKFLOW: true
        run: mvn clean package -DskipTests

      - name: Extract version from pom.xml
        id: extract_version
        working-directory: ./openapi/openapi-backend
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to DockerHub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      # ---------- Build & Push Backend Generator ----------
      - name: Build backend OpenAPI Docker image
        working-directory: ./openapi/openapi-backend
        run: |
          docker build -t ${DOCKERHUB_USERNAME}/openapi-backend:${VERSION} .
          docker tag ${DOCKERHUB_USERNAME}/openapi-backend:${VERSION} ${DOCKERHUB_USERNAME}/openapi-backend:latest

      - name: Push backend image
        run: |
          docker push ${DOCKERHUB_USERNAME}/openapi-backend:${VERSION}
          docker push ${DOCKERHUB_USERNAME}/openapi-backend:latest

      # ---------- Build & Push Frontend Generator ----------
      - name: Build frontend OpenAPI Docker image
        working-directory: ./openapi/openapi-frontend
        run: |
          docker build -t ${DOCKERHUB_USERNAME}/openapi-frontend:${VERSION} .
          docker tag ${DOCKERHUB_USERNAME}/openapi-frontend:${VERSION} ${DOCKERHUB_USERNAME}/openapi-frontend:latest

      - name: Push frontend image
        run: |
          docker push ${DOCKERHUB_USERNAME}/openapi-frontend:${VERSION}
          docker push ${DOCKERHUB_USERNAME}/openapi-frontend:latest
