name: Build and Push OpenAPI to DockerHub

on:
  workflow_dispatch:  # Permite lanzarlo manualmente desde la interfaz de GitHub

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: openapi
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build OpenAPI jar
        working-directory: ./openapi
        run: mvn clean package -DskipTests

      - name: Log in to DockerHub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build Docker image
        working-directory: ./openapi
        run: docker build -t ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest .

      - name: Push to DockerHub
        run: docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest