name: Build and Push OpenAPI to DockerHub

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: openapi
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build OpenAPI jar
        working-directory: ./openapi
        run: mvn clean package -DskipTests

      - name: Extract version from pom.xml
        id: extract_version
        working-directory: ./openapi
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to DockerHub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build Docker image with version tag
        working-directory: ./openapi
        run: |
          docker build -t ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${VERSION} .
          docker tag ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${VERSION} ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest

      - name: Push Docker images to DockerHub
        run: |
          docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${VERSION}
          docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest
